# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
# ko:
#  languageCode: ko-kr
#  contentDir: content/kr
#  title: Thanh-Tung Nguyen
#  params:
#    description: Bio in Korean
#  menu:
#    main:
#     - name: Bio
#       url: /
#       weight: 10
#     - name: Selected Publications
#       url: /#feat_papers
#       weight: 11
#     - name: Publications
#       url: /#papers
#       weight: 12
#     # - name: Talks
#     #   url: /#talks
#     #   weight: 12
#     - name: Experience
#       url: experience/
#       weight: 20
#     - name: News
#       url: /#news
#       weight: 13
#     # - name: Projects
#     #   url: projects/
#     #   weight: 30
#     - name: Mentoring
#       url: /#mentoring
#       weight: 40
