# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 1
  # - name: Selected Publications
  #   url: /#feat_papers
  #   weight: 11
  - name: News
    url: /#news
    weight: 2
  - name: Education
    url: /#education
    weight: 3
  - name: Publications
    url: /#papers
    weight: 4
  - name: Skills and Hobbies
    url: /#skills
    weight: 4
  - name: Teaching
    url: /#teaching
    weight: 5
  - name: Mentoring
    url: /#mentoring
    weight: 6
  # - name: Korean
  #   url: kr/
  #   weight: 50