# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  # - name: Selected Publications
  #   url: /#feat_papers
  #   weight: 11
  - name: Publications
    url: /#papers
    weight: 12
  - name: Education
    url: education/
    weight: 15
  - name: News
    url: /#news
    weight: 20
  # - name: Projects
  #   url: projects/
  #   weight: 30
  - name: Mentoring
    url: /#mentoring
    weight: 40
  # - name: Korean
  #   url: kr/
  #   weight: 50