params:
  people:
    - widget: people
      headless: true  # This is a headless section representing a page section.

      content:
        title: Mentoring
        # Choose which groups/teams of users to display.
        # Edit `user_groups` in each user's profile to add them to one or more of these groups.
        user_groups:
          - Mentees
      design:
        # Show user's social networking links? (true/false)
        show_social: false
        # Show user's interests? (true/false)
        show_interests: true
        # Show user's role?
        show_role: true
        # Show user's organizations/affiliations?
        show_organizations: true
